require("plugins")
require("setup")
-- require("lualine")
-- require("tabline")
require("custom.telescope")
-- require("custom.lspsaga")
require("custom.trouble")
-- require("custom.compe")
--require("ocgmode").setup_ts_grammar()
require("custom.snap")
require("lsp")
require("custom.cmp")
require("nvim-treesitter")
require("mappings")
require("custom.statusline.private_init")
require("comments")
require("custom.gitsigns")
require("custom.hydra-git")
require("custom.hydra-telescope")
require("custom.hydra-windows")
