require("plugins")
require("setup")
require("lualine")
require("tabline")
require("custom.telescope")
require("custom.lspsaga")
-- require("custom.compe")
require("custom.snap")
require("mappings")
require("lsp")
require("nvim-treesitter")
