require("plugins")
require("setup")
-- require("lualine")
-- require("tabline")
require("custom.telescope")
-- require("custom.lspsaga")
require("custom.trouble")
-- require("custom.compe")
require("custom.snap")
require("custom.cmp")
require("lsp")
require("nvim-treesitter")
require("mappings")
require("custom.statusline.private_init")
require("comments")
